Open url on iOS
amodm/webbrowser-rs pull request #48
Opened 2022-08-18 13:56 UTC by hakolao

Here's a PR that adds browser open on iOS opening the browser using `objc` crate.

I've only ran this with my own project using iPhone 8 Plus.

Tests are not covered.

2022-08-18 16:34 UTC, amodm requested changes
Thanks for landing the iOS support @hakolao. Long awaited! I've put in some comments about bringing consistency to code style. Subject to those, this is good to merge.

If you find the time, you can explore [tests/test_android.rs](https://github.com/amodm/webbrowser-rs/blob/main/tests/test_android.rs) to include a test for this. If not, I'll add it after the merge, but I'll need a github link to the test project you used locally. Appreciate the help on this.

2022-08-18 16:34 UTC, amodm commented on src/lib.rs
> +        #[cfg(not(target_os = "ios"))]
Handle this via the `BrowserOptions.dry_run` to use the same code pattern as in other platforms. See [android as an example](https://github.com/amodm/webbrowser-rs/blob/main/src/android.rs#L23)

2022-08-18 16:34 UTC, amodm commented on src/lib.rs
> +#[cfg(not(target_os = "ios"))]
This and other conditionals are not needed if the signature in `ios.rs` is modified appropriately.

2022-08-18 18:09 UTC, hakolao commented
I've now addressed the changes requested. [Here](https://github.com/hakolao/browser_open_ios) is an example project that only opens url on iOS after 2 seconds.

I use `cargo-mobile` to generate the xcode project and to run the builds.

2022-08-18 18:11 UTC, hakolao commented
> If you find the time, you can explore [tests/test_android.rs](https://github.com/amodm/webbrowser-rs/blob/main/tests/test_android.rs) to include a test for this

Unfortunately I won't have time for this currently, but I'll be eager to see what kind of a test setup you'll make for iOS.

2022-08-18 18:36 UTC, merged

2022-08-18 18:38 UTC, amodm commented
Congratulations on your first PR, @hakolao 🥳 

Windows build VM has been a bit unreliable, so I'm ignoring the test result (your code didn't touch it anyways). This will get released after I've had the time to write tests for ios.

2022-08-18 18:40 UTC, hakolao commented
Amazing! 🥳, thanks for the review!

2022-09-09 18:24 UTC, amodm commented
FYI, this is now out in [v0.8.0](https://github.com/amodm/webbrowser-rs/releases/tag/v0.8.0) release.

2022-09-09 18:54 UTC, hakolao commented
Amazing! :)